version: '2.4'
services:
  DiscordVoiceStatus:
    image: hedius/discordvoicestatus:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    ports:
      - "8080:8080"
    environment:
      VOICESTATUS_TOKEN: "YOUR_TOKEN"
      VOICESTATUS_HOST: "0.0.0.0"
      VOICESTATUS_PORT: 8080
      VOICESTATUS_LOAD_ALL: "True"